---
is_validator: true
validator_stake_amount: 100000

secp_private_key: "{{ vault_secp_private_key }}"
bls_private_key: "{{ vault_bls_private_key }}"
beneficiary_address: "{{ vault_beneficiary_address }}"
auth_address: "{{ vault_auth_address }}"

node_type: "validator"
